language: python

notifications:
    email: false

env: SKIP_INTERPRETER=true

before_install:
  - git clone https://github.com/TravisToolbox/pycodestyle-travis.git
  - pip install flask_testing

install:
  - ./pycodestyle-travis/install.sh

script:
  - ./pycodestyle-travis/scan.sh
  - python manage.py test