language: python

notifications:
    email: false

before_install:
  - pip install pycodestyle
  - pip install autopep8

script:
  - num_errors_before=`find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l`
  - echo $num_errors_before

  - cd "$TRAVIS_BUILD_DIR"
  - git config --global user.email "hugosmails94@gmail.com"
  - git config --global user.name "HugoDurand"
  - git checkout $TRAVIS_BRANCH

  - find . -name \*.py -exec autopep8 --recursive --aggressive --aggressive --in-place {} +
  - num_errors_after=`find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l`
  - echo $num_errors_after

  - |
    if (( $num_errors_after < $num_errors_before )); then
        git commit -a -m "PEP-8 Fix"
        git config --global push.default simple
        git push --quiet
    fi
  - cd "$TRAVIS_BUILD_DIR"
  - find . -name \*.py -exec pycodestyle --ignore=E402 {} +