version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - elasticsearch
    db:
        image: postgres:10-alpine
        env_file:
            - .env
        ports:
            - "5455:5432"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        ports:
            - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.0
        ports:
            - "5601:5601"
#        environment:
#            ELASTICSEARCH_HOSTS: http://0.0.0.0:9200
